### ISSUE TITLE
used to work well but can't get through after token updated

### ISSUE THREAD

**Issue by suredream** [jdowner/gist#101]
tried several times but no luck.

```
Traceback (most recent call last):
  File "/Users/jun.xiong/miniconda3/bin/gist", line 11, in <module>
    sys.exit(main())
  File "/Users/jun.xiong/miniconda3/lib/python3.6/site-packages/gist/client.py", line 405, in main
    token = get_personal_access_token(config)
  File "/Users/jun.xiong/miniconda3/lib/python3.6/site-packages/gist/client.py", line 288, in get_personal_access_token
    raise GistInvalidTokenError("Invalid personal access token")
gist.client.GistInvalidTokenError: Invalid personal access token
```

**Comment by jdowner** [comment]
Have you followed the instructions on getting a personal access token? https://github.com/jdowner/gist#getting-started

**Comment by suredream** [comment]
hi jdowner,  I did a couple of time of the PAT and also tried from my local and some cloud instance. Neither works.

I changed to [this client](https://github.com/defunkt/gist) and went through smoothly, so I assume it was not the problem of PAT.

However, I am still looking forward to using your tool since it looks awesome and more capabilities. Hopeful we can figure out why this issue happened.

Thanks for your great work!

**Comment by jdowner** [comment]
I think the problem is with the gist client code. There is a validation step that checks to make sure that your token conforms to a specific format. However, it looks like the format has changed so it is rejecting your token incorrectly. I'll put a fix up and you can see if that addresses the problem for you.

**Comment by jdowner** [comment]
@suredream I've pushed a fix to https://github.com/jdowner/gist/tree/bugfix Try it out and let me know if that resolved the problem for you!

**Comment by suredream** [comment]
That does make sense to me ... the token now starts with "ghp_*******".

I checked out the new branch with pip install .  but the same PAT error is still there.

**Comment by jdowner** [comment]
That's odd. Would you mind running `which gist` to make sure you're using the new version? That error has been remove so it should not be possible to get the same error even if something is going wrong.

**Comment by jdowner** [comment]
@suredream I'm going to close this ticket. I've removed the code that raises this error and published the fix in a new version of `gist` (v0.10.4). If you are still having problems with this new version, feel free to re-open this ticket or create a new one.
